name: Build and Release Mod

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          mkdir package
          cp modinfo.json package/
          cp modicon.png package/
          cp -r assets package/
          cd package
          zip -r ../layered-armors.zip .

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: layered-armors.zip